import type { SeedModule } from "./types";

export const STORIES: SeedModule[] = [
  { category: "story", variant_key: "A", weight: 1, body: "I built Productivity Shastra because I was the founder who was always-on, always-reactive, and always one Slack notification away from a system crash. The program is everything I wish I'd had — a system, not a syllabus." },
  { category: "story", variant_key: "B", weight: 1, body: "The 1,500-founder survey we ran made one thing brutally clear: knowledge isn't the bottleneck, implementation is. So the entire program is built around implementation, with alternate-day guided accountability." },
  { category: "story", variant_key: "C", weight: 1, body: "We measured 1,500+ founders across 200+ industries. The numbers that came back weren't motivational — they were structural: businesses grew 47%, hours dropped, focus sharpened. That's what we're trying to reproduce in the next cohort." },
  { category: "story", variant_key: "D", weight: 1, body: "Eight silent killers: firefighting, revenue plateau, team dependency, no systems, no strategic time, burnout, long hours, overwhelm. None of these are effort problems. Every one of them is a structure problem — and structure can be fixed." },
  { category: "story", variant_key: "E", weight: 1, body: "A founder I worked with last quarter told me: \"Manan, I used to dread Monday. Now I look at my week like a project manager would.\" That's the kind of shift the program is engineered to create." },
  { category: "story", variant_key: "F", weight: 1, body: "I learned this the hard way: as a CA, I watched dozens of founders who were brilliant at sales, brilliant at product, brilliant at hiring — and bankrupt at structure. Productivity Shastra is the structure I wish I'd handed them earlier." },
  { category: "story", variant_key: "G", weight: 1, body: "The Operating Shift is the spine of the program: a list of what to STOP doing, a list of what to START doing. It's almost embarrassingly simple — until you try to live it. Then the program kicks in." },
  { category: "story", variant_key: "H", weight: 1, body: "We don't do 'motivational' — and we don't do 'course videos you'll never watch.' Productivity Shastra is live workshops, alternate-day accountability, and done-for-you templates you actually open on Monday morning." },
  { category: "story", variant_key: "I", weight: 1, body: "A founder from the last cohort put it bluntly: 'The 6-week structure was the thing. Without it, this would've been another course on my hard drive.' Same program, structured differently — that's the difference." },
  { category: "story", variant_key: "J", weight: 1, body: "If you've read every productivity book and still feel busy, the missing piece is almost always the same: structure that survives contact with Monday morning. That's what we build inside the cohort." },
  { category: "story", variant_key: "K", weight: 1, body: "Mumbai-headquartered, but the cohort is fully remote-friendly. Founders from Bengaluru, Delhi, Singapore, and Dubai joined the last one. The only thing that has to be in the room is the willingness to implement." },
  { category: "story", variant_key: "L", weight: 1, body: "Productivity Shastra literally means 'the operating manual for a productive life.' I built it because the books I read gave me motivation, not structure. The structure is the product." },
];
